<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/oauth2/token");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "grant_type=client_credentials");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_USERPWD, "AakaY2FvGBHcNTNjfdOneGD8zMo9_fY2k7LQjY0OLTRduVmfD9tDmAxDooZMjIaVwazIQGe8Vyg5NwVx" . ":" . "EIN9qKRT7UP4mL44G3UJKq4j8gO-xYKQt6elRe_2IybV2NwHj0XeI1uncGeiS74rpsr9Gn3J4c5yiPGP");

$headers = array();
$headers[] = "Accept: application/json";
$headers[] = "Accept-Language: en_US";
$headers[] = "Content-Type: application/x-www-form-urlencoded";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
$result = json_decode($result);
// print_r(json_decode($result));die;
// print_r($result->access_token);die;
$token = $result->access_token;
$conn_string = "host=localhost port=5432 dbname=punchcard user=postgres password=p^5$3@1";
$dbconn = pg_connect($conn_string);

$query = pg_query($dbconn, "INSERT INTO access_token_test (secret_key) VALUES ('".$token."')");

?>