<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, "https://api.sandbox.paypal.com/v1/payments/payment");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"id\":\"CPPAY-13U467758H032001PKPIFQZI\",\n  \"intent\":\"sale\",\n  \"payer\":{\n    \"payment_method\":\"credit_card\",\n    \"funding_instruments\":[\n      {\n        \"credit_card_token\":{\n          \"credit_card_id\":\"CARD-22V11043V33077438LIHJOWQ\",\n          \"external_customer_id\":\"joe_shopper408-334-8890\"\n        }\n      }\n    ]\n  },\n  \"transactions\":[\n    {\n      \"amount\":{\n        \"total\":\"100.70\",\n        \"currency\":\"USD\"\n      },\n      \"description\":\"Payment by vaulted credit card.\"\n    }\n  ]\n}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = "Content-Type: application/json";
$headers[] = "Authorization: Bearer A21AAEiEziHgvb0oXHLoPN5eATkAuJ0hMkjxxCWqZhc1K8Xs4QHnHHtdiR9pCp0TuNBFyF0DENGAWF4VUqulOxOhYsN0ClxTg";
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

print_r($result);
?>